apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: oracle-mcp-server
  namespace: loki-toolhive-oracle-mcp
spec:
  image: quay.io/ecosystem-appeng/oracle-sqlcl-mcp-server:1.0.0
  permissionProfile:
    name: network
    type: builtin
  podTemplateSpec:
    metadata: {}
    spec:
      securityContext:
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
      volumes:
      - name: sqlcl-data
        persistentVolumeClaim:
          claimName: oracle-mcp-data
      containers:
      - name: mcp
        image: quay.io/ecosystem-appeng/oracle-sqlcl-mcp-server:1.0.0
        env:
        - name: HOME
          value: "/sqlcl-home"
        - name: JAVA_TOOL_OPTIONS
          value: ""
        - name: _JAVA_OPTIONS
          value: ""
        - name: ORACLE_USER
          value: "sales"
        - name: ORACLE_PASSWORD
          value: ""
        - name: ORACLE_CONNECTION_STRING
          value: "jdbc:oracle:thin:@<oracle-k8-service-name>:1521/FREEPDB1"
        - name: ORACLE_CONN_NAME
          value: "oracle_connection_demo1"
        volumeMounts:
        - name: sqlcl-data
          mountPath: /sqlcl-home


        # Custom image has MCP server as entry point
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        securityContext: 
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
  port: 8080
  transport: stdio