apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-mcp-data
  namespace: loki-toolhive-oracle-mcp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

