{{- $root := . }}
{{- $servers := include "mcp-servers.mergeMcpServers" . | fromJson }}
{{- range $key, $server := $servers }}
{{- if $server.enabled }}
{{- $serverDict := dict "root" $root "key" $key "server" $server }}
---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: {{ $key }}
  labels:
    {{- include "mcp-servers.labels" $serverDict | nindent 4 }}
spec:
  image: "{{ $server.image }}"
  permissionProfile:
    name: {{ $server.permissionProfile.name | default "network" }}
    type: {{ $server.permissionProfile.type | default "builtin" }}
  podTemplateSpec:
    metadata: {}
    spec:
      serviceAccountName: {{ include "mcp-servers.serviceAccountName" $serverDict }}
      {{- with $server.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if and $server.persistence $server.persistence.enabled }}
      - name: {{ $server.persistence.volumeName | default "data" }}
        ephemeral:
          volumeClaimTemplate:
            metadata:
              labels:
                {{- include "mcp-servers.labels" $serverDict | nindent 16 }}
            spec:
              accessModes:
                - {{ $server.persistence.accessMode }}
              resources:
                requests:
                  storage: {{ $server.persistence.size }}
              {{- if $server.persistence.storageClassName }}
              storageClassName: {{ $server.persistence.storageClassName }}
              {{- end }}
      {{- end }}
      {{- with $server.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq $key "oracle-sqlcl" }}
      initContainers:
      - name: wait-for-oracle
        image: "alpine/k8s:1.28.2"
        imagePullPolicy: "IfNotPresent"
        command:
          - /bin/sh
          - -c
          - |
            set -euo pipefail
            SECRET_NAME="oracle23ai"
            ORACLE_POD_NAME="oracle23ai-0"
            TPCDS_JOB_PREFIX="oracle23ai-tpcds-populate"
            NAMESPACE="{{ $root.Release.Namespace }}"
            TIMEOUT=1800
            INTERVAL=5
            echo "Init container: Waiting up to ${TIMEOUT}s for Oracle TPCDS populate job to complete..."
            start=$(date +%s)
            while true; do
              # Check if the secret exists (created when Oracle starts)
              if kubectl get secret "${SECRET_NAME}" -n "${NAMESPACE}" >/dev/null 2>&1; then
                echo "Secret ${SECRET_NAME} found. Checking Oracle pod readiness..."
                # Check if the Oracle pod is ready
                if kubectl get pod "${ORACLE_POD_NAME}" -n "${NAMESPACE}" -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' | grep -q "True"; then
                  echo "Oracle pod ${ORACLE_POD_NAME} is ready. Checking TPCDS populate job..."
                  # Check if TPCDS populate job exists and is completed
                  TPCDS_JOB=$(kubectl get pods -n "${NAMESPACE}" -l job-name="${TPCDS_JOB_PREFIX}" --field-selector=status.phase=Succeeded -o name | head -1)
                  if [ -n "${TPCDS_JOB}" ]; then
                    echo "TPCDS populate job completed successfully. Proceeding with MCPServer startup."
                    exit 0
                  else
                    echo "Oracle ready but TPCDS populate job not completed yet..."
                    # Show current TPCDS job status for debugging
                    kubectl get pods -n "${NAMESPACE}" -l job-name="${TPCDS_JOB_PREFIX}" || echo "No TPCDS job pods found yet"
                  fi
                else
                  echo "Secret exists but Oracle pod ${ORACLE_POD_NAME} not ready yet..."
                fi
              else
                echo "Secret ${SECRET_NAME} not yet created..."
              fi
              now=$(date +%s)
              elapsed=$(( now - start ))
              if [ $elapsed -ge $TIMEOUT ]; then
                echo "Oracle TPCDS populate job not completed after ${TIMEOUT}s"
                exit 1
              fi
              sleep ${INTERVAL}
            done
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      {{- end }}
      containers:
      - name: mcp
        image: "{{ $server.image }}"
        imagePullPolicy: {{ $server.imagePullPolicy | default "IfNotPresent" }}
        {{- if or $server.env $server.envSecrets }}
        env:
        {{- with $server.env }}
        {{- range $envKey, $envValue := . }}
        {{- if ne $envValue nil }}
        - name: {{ $envKey }}
          value: {{ $envValue | quote }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- with $server.envSecrets }}
        {{- range $envKey, $secretSpec := . }}
        - name: {{ $envKey }}
          valueFrom:
            secretKeyRef:
              name: {{ $secretSpec.name }}
              key: {{ $secretSpec.key }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- with $server.volumeMounts }}
        volumeMounts:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $server.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $server.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
  port: {{ $server.port | default 8080 }}
  {{- if $server.targetPort }}
  targetPort: {{ $server.targetPort }}
  {{- end }}
  transport: {{ $server.transport | default "stdio" }}
{{- end }}
{{- end }}