{{- $root := . }}
{{- $servers := include "mcp-servers.mergeMcpServers" . | fromJson }}
{{- range $key, $server := $servers }}
{{- if and $server.enabled (default false $server.createServiceAccount) (eq $key "oracle-sqlcl") }}
{{- $serverDict := dict "root" $root "key" $key "server" $server }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcp-servers.serviceAccountName" $serverDict }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "mcp-servers.labels" $serverDict | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
{{- end }}
