apiVersion: v2
name: oracle-sqlcl-mcp
description: Helm chart to deploy Oracle SQLcl MCP Server with Toolhive on OpenShift
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - oracle
  - sqlcl
  - mcp
  - toolhive
home: https://github.com/lokeshrangineni/ai-architecture-charts
sources:
  - https://github.com/lokeshrangineni/ai-architecture-charts
kubeVersion: ">=1.24.0-0"
